<?php
/**********************************************************************
    Copyright (C) FrontAccounting, LLC.
	Released under the terms of the GNU General Public License, GPL, 
	as published by the Free Software Foundation, either version 3 
	of the License, or (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
    See the License here <http://www.gnu.org/licenses/gpl-3.0.html>.
***********************************************************************/
include_once($path_to_root . "/includes/date_functions.inc");

include_once($path_to_root . "/modules/asset_register/includes/db/asset_types_db.inc");
include_once($path_to_root . "/modules/asset_register/includes/db/assets_db.inc");
include_once($path_to_root . "/modules/asset_register/includes/db/amortisation_db.inc");
include_once($path_to_root . "/modules/asset_register/includes/db/asset_valuations_db.inc");
include_once($path_to_root . "/modules/asset_register/includes/db/amortisation_post_db.inc");

?>
